version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: 'dev'
    working_dir: /home/web
    tty: true
    volumes:
      - ./app:/home/web
    ports:
      - 8088:80
