version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'web'
    working_dir: /home/web
    tty: true
    volumes:
      - ./app:/home/web
    ports:
      - 8088:80
